  - name: Add or Update Service
    kubernetes.core.k8s:
      kubeconfig: ~/.kube/config
      namespace: "{{ NAMESPACE }}"
      template: svc.yml.j2

  - name: Add or Update ServiceMonitor
    kubernetes.core.k8s:
      kubeconfig: ~/.kube/config
      namespace: "{{ NAMESPACE }}"
      template: svc-monitor.yml.j2

  - name: Add or Update Secret by 1Password
    kubernetes.core.k8s:
      kubeconfig: ~/.kube/config
      namespace: "{{ NAMESPACE }}"
      template: onepassword.yml.j2
  
  - name: Add or Update statefulSet
    kubernetes.core.k8s:
      kubeconfig: ~/.kube/config
      namespace: "{{ NAMESPACE }}"
      template: statefulset.yml.j2

  - name: Add or Update init Secret by 1Password
    kubernetes.core.k8s:
      kubeconfig: ~/.kube/config
      namespace: "{{ NAMESPACE }}"
      template: init-onepassword.yml.j2

  - name: Add or Update init Configmap
    kubernetes.core.k8s:
      kubeconfig: ~/.kube/config
      namespace: "{{ NAMESPACE }}"
      template: init-configmap.yml.j2

  - name: Add or Update init Job
    kubernetes.core.k8s:
      kubeconfig: ~/.kube/config
      namespace: "{{ NAMESPACE }}"
      template: init-job.yml.j2
